// <auto-generated />
using System;
using FR.BusinessObjects.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FR.BusinessObjects.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FR.BusinessObjects.Models.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("FR.BusinessObjects.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FoodScore")
                        .HasColumnType("integer");

                    b.Property<int>("ServingScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FR.BusinessObjects.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FoodCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xúc xích cỡ lớn 300g với đồ muối chua",
                            FoodCategoryId = 1,
                            ImageUrl = "big-beerfest-bausages.jpg",
                            Name = "BIG BEERFEST SAUSAGES",
                            Price = 199000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xúc xích Đức nướng ăn kèm salad rau tổng hợp",
                            FoodCategoryId = 1,
                            ImageUrl = "grilled-german-gausages.jpg",
                            Name = "GRILLED GERMAN SAUSAGES",
                            Price = 136000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bánh mì bơ tỏi",
                            FoodCategoryId = 1,
                            ImageUrl = "garlic-bread.jpg",
                            Name = "GARLIC BREAD",
                            Price = 30000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khoai tây chiên",
                            FoodCategoryId = 1,
                            ImageUrl = "french-fried.jpg",
                            Name = "FRENCH FRIED",
                            Price = 50000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cánh gà nướng BBQ ăn kèm Salad, khoai tây chiên (2 cánh)",
                            FoodCategoryId = 1,
                            ImageUrl = "chicken-wings.jpg",
                            Name = "CHICKEN WINGS",
                            Price = 86000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đĩa tổng hợp các loại khoai chiên",
                            FoodCategoryId = 1,
                            ImageUrl = "beer-batter-fries.jpg",
                            Name = "BEER BATTER FRIES",
                            Price = 99000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gan Ngỗng áp chảo cùng Mứt, sốt xoài và bánh mỳ Pháp nướng",
                            FoodCategoryId = 1,
                            ImageUrl = "pan-seared-foie-gras.jpg",
                            Name = "PAN SEARED FOIE-GRAS",
                            Price = 196000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quả ô-liu trộn cay 100gr",
                            FoodCategoryId = 1,
                            ImageUrl = "marinated-spicy-olives.jpg",
                            Name = "MARINATED SPICY OLIVES",
                            Price = 86000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lườn vịt xông khói với Mayonnaise mutat Dijon",
                            FoodCategoryId = 1,
                            ImageUrl = "smoked-duck.jpg",
                            Name = "SMOKED DUCK",
                            Price = 155000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bò tái kiểu Ý cùng rau rocket, phô mai bào",
                            FoodCategoryId = 1,
                            ImageUrl = "beef-carpaccio.jpg",
                            Name = "BEEF CARPACCIO",
                            Price = 180000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đùi lợn Tây Ban Nha Cebo cắt lát với dưa lưới và rau arugula",
                            FoodCategoryId = 1,
                            ImageUrl = "iberico-de-cebo.jpg",
                            Name = "IBERICO DE CEBO",
                            Price = 436000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Patê thịt Vịt phục vụ cùng mứt hoa quả và bánh mỳ Pháp",
                            FoodCategoryId = 1,
                            ImageUrl = "french-duck-rillette.jpg",
                            Name = "FRENCH DUCK RILLETTE",
                            Price = 136000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cá hồi xông khói nhà làm với bánh mỳ Pháp nướng, kem phô mai và rau cải xoăn",
                            FoodCategoryId = 1,
                            ImageUrl = "housemade-smoked-salmon.jpg",
                            Name = "HOUSEMADE SMOKED SALMON",
                            Price = 166000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thăn lưng Wagyu MB4/5 250g",
                            FoodCategoryId = 2,
                            ImageUrl = "aus-rib-eye-mb4-5.jpg",
                            Name = "AUS RIB EYE MB4/5",
                            Price = 1280000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thăn Flank Wagyu MB7/8 250g",
                            FoodCategoryId = 2,
                            ImageUrl = "aus-rib-eye-mb7-8.jpg",
                            Name = "AUS RIB EYE MB7/8",
                            Price = 660000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thǎn \"Mắc Áo\" Wagyu MB3 250g",
                            FoodCategoryId = 2,
                            ImageUrl = "aus-hanging-tender-mb3.jpg",
                            Name = "AUS HANGING TENDER MB3",
                            Price = 600000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thăn lưng bò Mỹ Prime 500g",
                            FoodCategoryId = 2,
                            ImageUrl = "us-prime-rib-eye.jpg",
                            Name = "US PRIME RIB EYE",
                            Price = 960000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thăn Bò Angus chữ T Úc 700g",
                            FoodCategoryId = 2,
                            ImageUrl = "aus-black-angus-t-bone.jpg",
                            Name = "AUS BLACK ANGUS T-BONE",
                            Price = 1160000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thăn nội bò Mỹ 250g",
                            FoodCategoryId = 2,
                            ImageUrl = "us-tenderloin.jpg",
                            Name = "US TENDERLOIN",
                            Price = 560000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thăn lưng bò Mỹ 350g",
                            FoodCategoryId = 2,
                            ImageUrl = "us-rib-eye.jpg",
                            Name = "US RIB EYE",
                            Price = 596000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thăn ngoại bò Mỹ 350g",
                            FoodCategoryId = 2,
                            ImageUrl = "us-striploin.jpg",
                            Name = "US STRIPLOIN",
                            Price = 386000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thăn nội bò Canada 200g",
                            FoodCategoryId = 2,
                            ImageUrl = "canada-tenderloin.jpg",
                            Name = "CANADA TENDERLOIN",
                            Price = 386000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thăn lưng bò Úc 250g",
                            FoodCategoryId = 2,
                            ImageUrl = "aus-rib-eye.jpg",
                            Name = "AUS RIB EYE",
                            Price = 246000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khoai tây nghiền",
                            FoodCategoryId = 3,
                            ImageUrl = "mashed-potato.jpg",
                            Name = "MASHED POTATO",
                            Price = 30000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nấm xào",
                            FoodCategoryId = 3,
                            ImageUrl = "saute-mushroom.jpg",
                            Name = "SAUTÉ MUSHROOM",
                            Price = 30000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khoai tây bi đút lò",
                            FoodCategoryId = 3,
                            ImageUrl = "roasted-baby-potato.jpg",
                            Name = "ROASTED BABY POTATO",
                            Price = 30000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đùi cừu nướng 2kg với thảo mộc",
                            FoodCategoryId = 2,
                            ImageUrl = "roasted-lamb-leg-2kg.jpg",
                            Name = "ROASTED LAMB LEG 2KG",
                            Price = 2600000f,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sườn cừu Úc thượng hạng nướng với thảo mộc",
                            FoodCategoryId = 2,
                            ImageUrl = "herbs-crusted-aus-lamb-rack.jpg",
                            Name = "HERBS CRUSTED AUS LAMB RACK",
                            Price = 580000f,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đùi vịt nấu chậm ăn kèm với khoai Roti, rau củ đút lò và sốt Gravy",
                            FoodCategoryId = 2,
                            ImageUrl = "duck-confit.jpg",
                            Name = "DUCK CONFIT",
                            Price = 246000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sườn lợn nướng BBQ (1,1 kg) với salad và khoai tây chiên",
                            FoodCategoryId = 2,
                            ImageUrl = "grilled-pork-rib-bbq.jpg",
                            Name = "GRILLED PORK RIB BBQ",
                            Price = 660000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cá ngừ nướng với sốt mayonnaise",
                            FoodCategoryId = 2,
                            ImageUrl = "tuna-steak.jpg",
                            Name = "TUNA STEAK",
                            Price = 166000f,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cá hồi áp chảo cùng cà rốt bào, cà rốt nghiền ăn với các lựa chọn sốt Cam Cà rốt, Kem Mù tạt",
                            FoodCategoryId = 2,
                            ImageUrl = "seared-salmon-fillet.jpg",
                            Name = "SEARED SALMON FILLET",
                            Price = 226000f,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salad cá hồi xông khói, xà lách, cải mầm, rau rocket, bánh mỳ giòn, sốt dầu dấm",
                            FoodCategoryId = 4,
                            ImageUrl = "smoked-salmon-salad.jpg",
                            Name = "SMOKED SALMON SALAD",
                            Price = 166000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sa Lát rau xanh tổng hợp với lựa chọn các sốt dấm Balsamic, sốt chanh leo, sốt Thousand Island",
                            FoodCategoryId = 4,
                            ImageUrl = "mix-green-salad.jpg",
                            Name = "MIX GREEN SALAD",
                            Price = 66000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salad trái cây với hạt Chia và các lựa chọn sốt sữa chua chanh leo, sốt Thousand Island",
                            FoodCategoryId = 4,
                            ImageUrl = "tropical-fruit-salad.jpg",
                            Name = "TROPICAL FRUIT SALAD",
                            Price = 80000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lườn vịt xông khói xà lách, rau rocket, hoa quả, cam và sốt dầm Ý",
                            FoodCategoryId = 4,
                            ImageUrl = "orange-salad-with-smoke-duck.jpg",
                            Name = "ORANGE SALAD WITH SMOKE DUCK",
                            Price = 106000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salad Wakame với dưa chuột bào, rong nho biển, trứng cua sốt mè",
                            FoodCategoryId = 4,
                            ImageUrl = "ocean-seaweed-salad.jpg",
                            Name = "OCEAN SEAWEED SALAD",
                            Price = 98000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salad ăn kèm trứng cút, ba rọi xông khói, phô mai bào, bánh mỳ giòn và sốt Caesar",
                            FoodCategoryId = 4,
                            ImageUrl = "caesar-salad.jpg",
                            Name = "CAESAR SALAD",
                            Price = 86000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salad cá ngừ tươi cùng với khoai tây bi, trứng cút, đậu Pháp, củ cải đỏ, cà chua sấy và sốt dầu dấm",
                            FoodCategoryId = 4,
                            ImageUrl = "nicoise-salad.jpg",
                            Name = "NICOISE SALAD",
                            Price = 126000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Súp nấm kem",
                            FoodCategoryId = 5,
                            ImageUrl = "creamy-mushroom-soup.jpg",
                            Name = "CREAMY MUSHROOM SOUP",
                            Price = 80000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Súp kem bí đỏ kèm hạt bí nướng giòn, kem chua",
                            FoodCategoryId = 5,
                            ImageUrl = "creamy-pumpkin-soup.jpg",
                            Name = "CREAMY PUMPKIN SOUP",
                            Price = 60000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sốt vang đỏ",
                            FoodCategoryId = 6,
                            ImageUrl = "red-wine-sauce.jpg",
                            Name = "RED WINE SAUCE",
                            Price = 25000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sốt tiêu",
                            FoodCategoryId = 6,
                            ImageUrl = "pepper-sauce.jpg",
                            Name = "PEPPER SAUCE",
                            Price = 25000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sốt nấm",
                            FoodCategoryId = 6,
                            ImageUrl = "mushroom-sauce.jpg",
                            Name = "MUSHROOM SAUCE",
                            Price = 25000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sốt bơ tỏi",
                            FoodCategoryId = 6,
                            ImageUrl = "garlic-butter-sauce.jpg",
                            Name = "GARLIC BUTTER SAUCE",
                            Price = 25000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sốt mù tạt",
                            FoodCategoryId = 6,
                            ImageUrl = "mustard-sauce.jpg",
                            Name = "MUSTARD SAUCE",
                            Price = 25000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sốt BBQ",
                            FoodCategoryId = 6,
                            ImageUrl = "bbq-sauce.jpg",
                            Name = "BBQ SAUCE",
                            Price = 25000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sốt phô mai xanh",
                            FoodCategoryId = 6,
                            ImageUrl = "creamy-blue-cheese-sauce.jpg",
                            Name = "CREAMY BLUE CHEESE SAUCE",
                            Price = 25000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sót Teriyaki",
                            FoodCategoryId = 6,
                            ImageUrl = "teriyaki-sauce.jpg",
                            Name = "TERIYAKI SAUCE",
                            Price = 25000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Coca Cola",
                            FoodCategoryId = 7,
                            ImageUrl = "coca-cola.jpg",
                            Name = "COCA COLA",
                            Price = 30000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước suối",
                            FoodCategoryId = 7,
                            ImageUrl = "tapid-water.jpg",
                            Name = "TAPID WATER",
                            Price = 20000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sinh tố dưa hấu",
                            FoodCategoryId = 7,
                            ImageUrl = "sinh-to-dua-hau.jpg",
                            Name = "SINH TỐ DƯA HẤU",
                            Price = 50000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fanta",
                            FoodCategoryId = 7,
                            ImageUrl = "fanta.jpg",
                            Name = "FANTA",
                            Price = 30000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sprite",
                            FoodCategoryId = 7,
                            ImageUrl = "sprite.jpg",
                            Name = "SPRITE",
                            Price = 30000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vang đỏ Barolo",
                            FoodCategoryId = 7,
                            ImageUrl = "barola.jpg",
                            Name = "BAROLA",
                            Price = 1200000f,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vang đỏ Chateau Leoville Poyferre",
                            FoodCategoryId = 7,
                            ImageUrl = "chateau-leoville-poyferre.jpg",
                            Name = "CHATEAU LEOVILLE POYFERRE",
                            Price = 1400000f,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vang đỏ Malbec",
                            FoodCategoryId = 7,
                            ImageUrl = "malbec.jpg",
                            Name = "MALBEC",
                            Price = 1700000f,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kem cháy gừng cùng với bánh quy giòn",
                            FoodCategoryId = 8,
                            ImageUrl = "ginger-cream-brulee.jpg",
                            Name = "GINGER CREAM BRULEE",
                            Price = 46000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bánh chocolate nướng chảy, kem vanilla và dừa sấy",
                            FoodCategoryId = 8,
                            ImageUrl = "warm-chocolate-lava-cake.jpg",
                            Name = "WARM CHOCOLATE LAVA CAKE",
                            Price = 50000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đĩa trái cây theo mùa",
                            FoodCategoryId = 8,
                            ImageUrl = "seasonal-fresh-fruit-plater.jpg",
                            Name = "SEASONAL FRESH FRUIT PLATER",
                            Price = 135000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bánh kem Ý hương lá nếp cùng chocolate nướng giòn và kem đánh bông",
                            FoodCategoryId = 8,
                            ImageUrl = "pandan-panna-cotta.jpg",
                            Name = "PANDAN PANNA-COTTA",
                            Price = 35000f,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kem Haagen Dazs, chocolate, vanilla, red berries, macha, Maccadmia nut",
                            FoodCategoryId = 8,
                            ImageUrl = "ice-cream-haagen-dazs.jpg",
                            Name = "ICE CREAM HAAGEN DAZS",
                            Price = 88000f,
                            Quantity = 100
                        });
                });

            modelBuilder.Entity("FR.BusinessObjects.Models.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Món khai vị"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Món chính"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Đồ ăn kèm"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Salad"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Soup"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Nước sốt"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Đồ uống"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Món tráng miệng"
                        });
                });

            modelBuilder.Entity("FR.BusinessObjects.Models.FoodLabels", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int>("LabelId")
                        .HasColumnType("integer");

                    b.HasKey("FoodId", "LabelId");

                    b.ToTable("FoodLabels");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            LabelId = 2
                        },
                        new
                        {
                            FoodId = 1,
                            LabelId = 6
                        },
                        new
                        {
                            FoodId = 1,
                            LabelId = 20
                        },
                        new
                        {
                            FoodId = 2,
                            LabelId = 2
                        },
                        new
                        {
                            FoodId = 2,
                            LabelId = 6
                        },
                        new
                        {
                            FoodId = 2,
                            LabelId = 20
                        },
                        new
                        {
                            FoodId = 3,
                            LabelId = 2
                        },
                        new
                        {
                            FoodId = 4,
                            LabelId = 2
                        },
                        new
                        {
                            FoodId = 4,
                            LabelId = 6
                        },
                        new
                        {
                            FoodId = 4,
                            LabelId = 20
                        },
                        new
                        {
                            FoodId = 5,
                            LabelId = 2
                        },
                        new
                        {
                            FoodId = 5,
                            LabelId = 5
                        },
                        new
                        {
                            FoodId = 5,
                            LabelId = 6
                        },
                        new
                        {
                            FoodId = 5,
                            LabelId = 27
                        },
                        new
                        {
                            FoodId = 6,
                            LabelId = 2
                        },
                        new
                        {
                            FoodId = 6,
                            LabelId = 6
                        },
                        new
                        {
                            FoodId = 6,
                            LabelId = 20
                        },
                        new
                        {
                            FoodId = 7,
                            LabelId = 2
                        },
                        new
                        {
                            FoodId = 8,
                            LabelId = 7
                        },
                        new
                        {
                            FoodId = 8,
                            LabelId = 8
                        },
                        new
                        {
                            FoodId = 8,
                            LabelId = 29
                        },
                        new
                        {
                            FoodId = 9,
                            LabelId = 2
                        },
                        new
                        {
                            FoodId = 9,
                            LabelId = 7
                        },
                        new
                        {
                            FoodId = 10,
                            LabelId = 3
                        },
                        new
                        {
                            FoodId = 10,
                            LabelId = 21
                        },
                        new
                        {
                            FoodId = 11,
                            LabelId = 26
                        },
                        new
                        {
                            FoodId = 12,
                            LabelId = 3
                        },
                        new
                        {
                            FoodId = 13,
                            LabelId = 3
                        },
                        new
                        {
                            FoodId = 13,
                            LabelId = 24
                        },
                        new
                        {
                            FoodId = 14,
                            LabelId = 23
                        },
                        new
                        {
                            FoodId = 15,
                            LabelId = 23
                        },
                        new
                        {
                            FoodId = 16,
                            LabelId = 23
                        },
                        new
                        {
                            FoodId = 17,
                            LabelId = 23
                        },
                        new
                        {
                            FoodId = 18,
                            LabelId = 23
                        },
                        new
                        {
                            FoodId = 19,
                            LabelId = 22
                        },
                        new
                        {
                            FoodId = 20,
                            LabelId = 22
                        },
                        new
                        {
                            FoodId = 21,
                            LabelId = 21
                        },
                        new
                        {
                            FoodId = 22,
                            LabelId = 21
                        },
                        new
                        {
                            FoodId = 23,
                            LabelId = 21
                        },
                        new
                        {
                            FoodId = 24,
                            LabelId = 1
                        },
                        new
                        {
                            FoodId = 24,
                            LabelId = 2
                        },
                        new
                        {
                            FoodId = 24,
                            LabelId = 8
                        },
                        new
                        {
                            FoodId = 25,
                            LabelId = 1
                        },
                        new
                        {
                            FoodId = 25,
                            LabelId = 8
                        },
                        new
                        {
                            FoodId = 26,
                            LabelId = 1
                        },
                        new
                        {
                            FoodId = 26,
                            LabelId = 8
                        },
                        new
                        {
                            FoodId = 27,
                            LabelId = 5
                        },
                        new
                        {
                            FoodId = 27,
                            LabelId = 25
                        },
                        new
                        {
                            FoodId = 28,
                            LabelId = 5
                        },
                        new
                        {
                            FoodId = 28,
                            LabelId = 25
                        },
                        new
                        {
                            FoodId = 29,
                            LabelId = 28
                        },
                        new
                        {
                            FoodId = 30,
                            LabelId = 5
                        },
                        new
                        {
                            FoodId = 30,
                            LabelId = 26
                        },
                        new
                        {
                            FoodId = 31,
                            LabelId = 5
                        },
                        new
                        {
                            FoodId = 31,
                            LabelId = 24
                        },
                        new
                        {
                            FoodId = 32,
                            LabelId = 5
                        },
                        new
                        {
                            FoodId = 32,
                            LabelId = 24
                        },
                        new
                        {
                            FoodId = 33,
                            LabelId = 24
                        },
                        new
                        {
                            FoodId = 34,
                            LabelId = 1
                        },
                        new
                        {
                            FoodId = 34,
                            LabelId = 8
                        },
                        new
                        {
                            FoodId = 35,
                            LabelId = 1
                        },
                        new
                        {
                            FoodId = 35,
                            LabelId = 8
                        },
                        new
                        {
                            FoodId = 36,
                            LabelId = 28
                        },
                        new
                        {
                            FoodId = 37,
                            LabelId = 1
                        },
                        new
                        {
                            FoodId = 37,
                            LabelId = 8
                        },
                        new
                        {
                            FoodId = 38,
                            LabelId = 8
                        },
                        new
                        {
                            FoodId = 38,
                            LabelId = 26
                        },
                        new
                        {
                            FoodId = 39,
                            LabelId = 1
                        },
                        new
                        {
                            FoodId = 40,
                            LabelId = 4
                        },
                        new
                        {
                            FoodId = 41,
                            LabelId = 4
                        },
                        new
                        {
                            FoodId = 42,
                            LabelId = 19
                        },
                        new
                        {
                            FoodId = 43,
                            LabelId = 19
                        },
                        new
                        {
                            FoodId = 44,
                            LabelId = 19
                        },
                        new
                        {
                            FoodId = 45,
                            LabelId = 19
                        },
                        new
                        {
                            FoodId = 46,
                            LabelId = 19
                        },
                        new
                        {
                            FoodId = 47,
                            LabelId = 19
                        },
                        new
                        {
                            FoodId = 48,
                            LabelId = 19
                        },
                        new
                        {
                            FoodId = 49,
                            LabelId = 19
                        },
                        new
                        {
                            FoodId = 50,
                            LabelId = 15
                        },
                        new
                        {
                            FoodId = 51,
                            LabelId = 15
                        },
                        new
                        {
                            FoodId = 52,
                            LabelId = 14
                        },
                        new
                        {
                            FoodId = 53,
                            LabelId = 15
                        },
                        new
                        {
                            FoodId = 54,
                            LabelId = 15
                        },
                        new
                        {
                            FoodId = 55,
                            LabelId = 18
                        },
                        new
                        {
                            FoodId = 56,
                            LabelId = 18
                        },
                        new
                        {
                            FoodId = 57,
                            LabelId = 18
                        },
                        new
                        {
                            FoodId = 58,
                            LabelId = 3
                        },
                        new
                        {
                            FoodId = 58,
                            LabelId = 12
                        },
                        new
                        {
                            FoodId = 59,
                            LabelId = 11
                        },
                        new
                        {
                            FoodId = 60,
                            LabelId = 1
                        },
                        new
                        {
                            FoodId = 60,
                            LabelId = 8
                        },
                        new
                        {
                            FoodId = 60,
                            LabelId = 29
                        },
                        new
                        {
                            FoodId = 61,
                            LabelId = 11
                        },
                        new
                        {
                            FoodId = 62,
                            LabelId = 12
                        });
                });

            modelBuilder.Entity("FR.BusinessObjects.Models.FoodOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<string>("FoodNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "FoodId");

                    b.ToTable("FoodOrder");
                });

            modelBuilder.Entity("FR.BusinessObjects.Models.Labels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Labels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Món chay"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Món nóng"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Món lạnh"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Món nước"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Món nướng"
                        },
                        new
                        {
                            Id = 6,
                            Label = "Thức ăn nhanh"
                        },
                        new
                        {
                            Id = 7,
                            Label = "Món cay"
                        },
                        new
                        {
                            Id = 8,
                            Label = "Dành cho người ăn kiêng"
                        },
                        new
                        {
                            Id = 9,
                            Label = "Dành cho người tập gym"
                        },
                        new
                        {
                            Id = 10,
                            Label = "Dành cho dịp lễ"
                        },
                        new
                        {
                            Id = 11,
                            Label = "Bánh"
                        },
                        new
                        {
                            Id = 12,
                            Label = "Kem"
                        },
                        new
                        {
                            Id = 13,
                            Label = "Nước ép"
                        },
                        new
                        {
                            Id = 14,
                            Label = "Sinh tố"
                        },
                        new
                        {
                            Id = 15,
                            Label = "Nước ngọt"
                        },
                        new
                        {
                            Id = 16,
                            Label = "Trà"
                        },
                        new
                        {
                            Id = 17,
                            Label = "Bia"
                        },
                        new
                        {
                            Id = 18,
                            Label = "Rượu vang"
                        },
                        new
                        {
                            Id = 19,
                            Label = "Nước chấm"
                        },
                        new
                        {
                            Id = 20,
                            Label = "Món chiên rán"
                        },
                        new
                        {
                            Id = 21,
                            Label = "Bò tiêu chuẩn"
                        },
                        new
                        {
                            Id = 22,
                            Label = "Bò cao cấp"
                        },
                        new
                        {
                            Id = 23,
                            Label = "Bò thượng hạng"
                        },
                        new
                        {
                            Id = 24,
                            Label = "Hải sản"
                        },
                        new
                        {
                            Id = 25,
                            Label = "Thịt cừu"
                        },
                        new
                        {
                            Id = 26,
                            Label = "Thịt lợn"
                        },
                        new
                        {
                            Id = 27,
                            Label = "Thịt gà"
                        },
                        new
                        {
                            Id = 28,
                            Label = "Thịt vịt"
                        },
                        new
                        {
                            Id = 29,
                            Label = "Trái cây"
                        });
                });

            modelBuilder.Entity("FR.BusinessObjects.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FR.BusinessObjects.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "In progress"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Finished"
                        });
                });

            modelBuilder.Entity("FR.BusinessObjects.Models.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e7a7e3d-4dac-4c2b-a67f-02e3be08b831"),
                            Name = "Bàn 1",
                            StatusId = 2
                        },
                        new
                        {
                            Id = new Guid("1624794a-e759-493b-b896-8d5997ebfacb"),
                            Name = "Bàn 2",
                            StatusId = 2
                        },
                        new
                        {
                            Id = new Guid("91fd3cf6-eb4e-4ee3-9093-5fc83c98354d"),
                            Name = "Bàn 3",
                            StatusId = 2
                        },
                        new
                        {
                            Id = new Guid("a2019937-caaa-4a8b-816d-a433bed1b497"),
                            Name = "Bàn 4",
                            StatusId = 2
                        },
                        new
                        {
                            Id = new Guid("0479eb67-3c7b-42df-bb0b-9ec46fc160cc"),
                            Name = "Bàn 5",
                            StatusId = 2
                        },
                        new
                        {
                            Id = new Guid("0028d2e6-2502-4567-8533-9b935c5c0a7f"),
                            Name = "Bàn 6",
                            StatusId = 1
                        },
                        new
                        {
                            Id = new Guid("7740180b-5dfe-42e2-a9ea-8fd47d04f72e"),
                            Name = "Bàn 7",
                            StatusId = 1
                        },
                        new
                        {
                            Id = new Guid("0fb60b7c-e7d0-47a2-a120-d4ba5b47e7f7"),
                            Name = "Bàn 8",
                            StatusId = 1
                        },
                        new
                        {
                            Id = new Guid("4ca5b6f4-2ab8-498f-9e4a-43f10e0be773"),
                            Name = "Bàn 9",
                            StatusId = 1
                        },
                        new
                        {
                            Id = new Guid("c39d30c5-f716-4a55-8be6-5f9f0437f895"),
                            Name = "Bàn 10",
                            StatusId = 3
                        },
                        new
                        {
                            Id = new Guid("5049c8a2-c907-4e95-8f9f-6412f4bf9c39"),
                            Name = "Bàn 11",
                            StatusId = 3
                        },
                        new
                        {
                            Id = new Guid("3fa20d35-b649-4d6f-993d-227561ce08b1"),
                            Name = "Bàn 12",
                            StatusId = 3
                        });
                });

            modelBuilder.Entity("FR.BusinessObjects.Models.TableStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TableStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Serving"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Booked"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
