// <auto-generated />
using System;
using MAGOI.BusinessObjects.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MAGOI.BusinessObjects.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240113163001_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillId"));

                    b.Property<int>("BillStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.HasKey("BillId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("BusinessObjects.Models.BillStatus", b =>
                {
                    b.Property<int>("BillStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillStatusID"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BillStatusID");

                    b.ToTable("BillStatus");
                });

            modelBuilder.Entity("BusinessObjects.Models.FoodOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "FoodId");

                    b.ToTable("FoodOrder");
                });

            modelBuilder.Entity("BusinessObjects.Models.OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderStatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderStatusId");

                    b.ToTable("OrderStatus");
                });

            modelBuilder.Entity("BusinessObjects.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("BusinessObjects.Models.PermissionResource", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.HasKey("PermissionId", "ResourceId");

                    b.ToTable("PermissionResource");
                });

            modelBuilder.Entity("BusinessObjects.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResourceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ResourceId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("BusinessObjects.Models.RestaurantCategory", b =>
                {
                    b.Property<int>("RestaurantCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RestaurantCategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RestaurantCategoryId");

                    b.ToTable("RestaurantCategories");

                    b.HasData(
                        new
                        {
                            RestaurantCategoryId = 1,
                            Description = "Nhà hàng chuyên về các món lẩu.",
                            Name = "Nhà hàng Lẩu"
                        },
                        new
                        {
                            RestaurantCategoryId = 2,
                            Description = "Nhà hàng chuyên về các món phở.",
                            Name = "Nhà hàng Phở"
                        },
                        new
                        {
                            RestaurantCategoryId = 3,
                            Description = "Nhà hàng chuyên về các món steak.",
                            Name = "Nhà hàng Steak"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BusinessObjects.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("BusinessObjects.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessObjects.Models.UserFoodWishlist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "FoodId");

                    b.ToTable("UserFoodWishlist");
                });

            modelBuilder.Entity("BusinessObjects.Models.UserRestaurant", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RestaurantId");

                    b.ToTable("UserRestaurant");
                });

            modelBuilder.Entity("MAGOI.BusinessObjects.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FoodCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu tôm với hương vị đậm đà của nước lẩu Tom Yum.",
                            FoodCategoryId = 1,
                            ImageUrl = "tomyum_goong.jpg",
                            IsAvailable = true,
                            Name = "Tom Yum Goong",
                            Price = 250000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 2,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu gà với hương vị đậm đà của nước lẩu Tom Yum.",
                            FoodCategoryId = 1,
                            ImageUrl = "tomyum_gai.jpg",
                            IsAvailable = true,
                            Name = "Tom Yum Gai",
                            Price = 320000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 3,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu hải sản với hương vị đậm đà của nước lẩu Tom Yum.",
                            FoodCategoryId = 1,
                            ImageUrl = "tomyum_talay.jpg",
                            IsAvailable = true,
                            Name = "Tom Yum Talay",
                            Price = 180000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 4,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu tôm với hương vị đậm đà của nước lẩu Tom Kha và sữa cô cocon",
                            FoodCategoryId = 2,
                            ImageUrl = "tomkha_goong.jpg",
                            IsAvailable = true,
                            Name = "Tom Kha Goong",
                            Price = 160000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 5,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu gà với hương vị đậm đà của nước lẩu Tom Kha và với sữa cô cocon",
                            FoodCategoryId = 2,
                            ImageUrl = "tomkha_gai.jpg",
                            IsAvailable = true,
                            Name = "Tom Kha Gai",
                            Price = 130000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 6,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu hải sản với hương vị đậm đà của nước lẩu Tom Kha và sữa cô cocon",
                            FoodCategoryId = 2,
                            ImageUrl = "tomkha_talay.jpg",
                            IsAvailable = true,
                            Name = "Tom Kha Talay",
                            Price = 190000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 7,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu tôm xanh với hương vị đậm đà của nước lẩu Green Curry.",
                            FoodCategoryId = 3,
                            ImageUrl = "greencurry_goong.jpg",
                            IsAvailable = true,
                            Name = "Green Curry Goong",
                            Price = 170000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 8,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu gà với hương vị đậm đà của nước lẩu Green Curry.",
                            FoodCategoryId = 3,
                            ImageUrl = "greencurry_gai.jpg",
                            IsAvailable = true,
                            Name = "Green Curry Gai",
                            Price = 140000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 9,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu hải sản với hương vị đậm đà của nước lẩu Green Curry.",
                            FoodCategoryId = 3,
                            ImageUrl = "greencurry_talay.jpg",
                            IsAvailable = true,
                            Name = "Green Curry Talay",
                            Price = 200000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 10,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu tôm cay với hương vị đậm đà của nước lẩu Red Curry.",
                            FoodCategoryId = 4,
                            ImageUrl = "spicy_redcurry_goong.jpg",
                            IsAvailable = true,
                            Name = "Spicy Red Curry Goong",
                            Price = 200000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 11,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu nấm với hương vị đậm đà của nước lẩu Red Curry.",
                            FoodCategoryId = 4,
                            ImageUrl = "redcurry_mushroom.jpg",
                            IsAvailable = true,
                            Name = "Red Curry Mushroom",
                            Price = 170000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 12,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu tôm cay với hương vị đậm đà của nước lẩu Massaman.",
                            FoodCategoryId = 6,
                            ImageUrl = "spicy_massaman_goong.jpg",
                            IsAvailable = true,
                            Name = "Spicy Massaman Curry Goong",
                            Price = 210000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 13,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lẩu gà với hương vị đậm đà của nước lẩu Massaman.",
                            FoodCategoryId = 6,
                            ImageUrl = "massaman_chicken.jpg",
                            IsAvailable = true,
                            Name = "Massaman Curry Chicken",
                            Price = 180000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 14,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở bò với thịt bò tái mềm ngon.",
                            FoodCategoryId = 7,
                            ImageUrl = "phobo_tai.jpg",
                            IsAvailable = true,
                            Name = "Phở Bò Tái",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 15,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở bò với thịt bò tái và chín mềm ngon.",
                            FoodCategoryId = 7,
                            ImageUrl = "phobo_taichin.jpg",
                            IsAvailable = true,
                            Name = "Phở Bò Tái Chín",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 16,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở bò với thịt bò chín mềm ngon.",
                            FoodCategoryId = 7,
                            ImageUrl = "phobo_chin.jpg",
                            IsAvailable = true,
                            Name = "Phở Bò Chín",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 17,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở bò với thịt bò nạm mềm ngon.",
                            FoodCategoryId = 7,
                            ImageUrl = "phobo_nam.jpg",
                            IsAvailable = true,
                            Name = "Phở Bò Nạm",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 18,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở bò với thịt bò gân mềm ngon.",
                            FoodCategoryId = 7,
                            ImageUrl = "phobo_gan.jpg",
                            IsAvailable = true,
                            Name = "Phở Bò Gân",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 19,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở bò với thịt bò sách mềm ngon.",
                            FoodCategoryId = 7,
                            ImageUrl = "phobo_sach.jpg",
                            IsAvailable = true,
                            Name = "Phở Bò Sách",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 20,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở gà với thịt gà đùi mềm ngon.",
                            FoodCategoryId = 8,
                            ImageUrl = "phoga_dui.jpg",
                            IsAvailable = true,
                            Name = "Phở Gà Đùi",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 21,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở gà với thịt gà lườn mềm ngon.",
                            FoodCategoryId = 8,
                            ImageUrl = "phoga_luon.jpg",
                            IsAvailable = true,
                            Name = "Phở Gà Lườn",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 22,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở gà với thịt gà cánh mềm ngon.",
                            FoodCategoryId = 8,
                            ImageUrl = "phoga_canh.jpg",
                            IsAvailable = true,
                            Name = "Phở Gà Cánh",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 23,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở gà với thịt gà và tim cật.",
                            FoodCategoryId = 8,
                            ImageUrl = "phoga_timcat.jpg",
                            IsAvailable = true,
                            Name = "Phở Gà Tim Cật",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 24,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở chay với nước dùng và đậu hũ.",
                            FoodCategoryId = 9,
                            ImageUrl = "phochay_dauhu.jpg",
                            IsAvailable = true,
                            Name = "Phở Chay Đậu Hũ",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 25,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở chay với nước dùng và đậu hũ.",
                            FoodCategoryId = 9,
                            ImageUrl = "phochay_nam.jpg",
                            IsAvailable = true,
                            Name = "Phở Chay Nấm",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 26,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở với sườn bò mềm ngon.",
                            FoodCategoryId = 10,
                            ImageUrl = "phosuon_bo.jpg",
                            IsAvailable = true,
                            Name = "Phở Sườn Bò",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 27,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở với sườn heo mềm ngon.",
                            FoodCategoryId = 10,
                            ImageUrl = "phosuon_heo.jpg",
                            IsAvailable = true,
                            Name = "Phở Sườn Heo",
                            Price = 50000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 28,
                            CreatedAt = new DateTime(2015, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salad trộn với rau sống và sốt truyền thống.",
                            FoodCategoryId = 11,
                            ImageUrl = "salad_tron.jpg",
                            IsAvailable = true,
                            Name = "Salad Trộn",
                            Price = 50000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 29,
                            CreatedAt = new DateTime(2015, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salad với cá ngừ và sốt truyền thống.",
                            FoodCategoryId = 11,
                            ImageUrl = "salad_cangu.jpg",
                            IsAvailable = true,
                            Name = "Salad Cá Ngừ",
                            Price = 50000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 30,
                            CreatedAt = new DateTime(2015, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salad gà và bơ avocado với sốt vinaigrette.",
                            FoodCategoryId = 11,
                            ImageUrl = "chicken_avocado_salad.jpg",
                            IsAvailable = true,
                            Name = "Chicken Avocado Salad",
                            Price = 70000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 31,
                            CreatedAt = new DateTime(2015, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salad Caesar truyền thống với sốt mayonnaise và phô mai.",
                            FoodCategoryId = 11,
                            ImageUrl = "caesar_salad.jpg",
                            IsAvailable = true,
                            Name = "Caesar Salad",
                            Price = 90000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 32,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bánh mì tỏi nướng giòn thơm phức.",
                            FoodCategoryId = 12,
                            ImageUrl = "garlic_bread.jpg",
                            IsAvailable = true,
                            Name = "Garlic Bread",
                            Price = 50000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 33,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cocktail tôm tươi ngon với sốt cay lạnh.",
                            FoodCategoryId = 12,
                            ImageUrl = "shrimp_cocktail.jpg",
                            IsAvailable = true,
                            Name = "Shrimp Cocktail",
                            Price = 120000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 34,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bruschetta nấm phô mai với dầu ôliu.",
                            FoodCategoryId = 12,
                            ImageUrl = "mushroom_bruschetta.jpg",
                            IsAvailable = true,
                            Name = "Mushroom Bruschetta",
                            Price = 90000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 35,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vỏ khoai tây nướng với phô mai và thịt xông khói.",
                            FoodCategoryId = 12,
                            ImageUrl = "potato_skins.jpg",
                            IsAvailable = true,
                            Name = "Potato Skins",
                            Price = 110000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 36,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ớt chuông nhồi phô mai, nướng giòn.",
                            FoodCategoryId = 12,
                            ImageUrl = "cheese_stuffed_jalapenos.jpg",
                            IsAvailable = true,
                            Name = "Cheese Stuffed Jalapeños",
                            Price = 95000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 37,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tartare cá ngừ với sốt hạt tiêu và cần tây.",
                            FoodCategoryId = 12,
                            ImageUrl = "tuna_tartare.jpg",
                            IsAvailable = true,
                            Name = "Tuna Tartare",
                            Price = 120000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 38,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ceviche tôm với cà chua, dưa leo, và hành tây.",
                            FoodCategoryId = 12,
                            ImageUrl = "shrimp_ceviche.jpg",
                            IsAvailable = true,
                            Name = "Shrimp Ceviche",
                            Price = 110000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 39,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đĩa cá hồi hút khói phục vụ với bánh mì và kem cheese.",
                            FoodCategoryId = 12,
                            ImageUrl = "smoked_salmon_platter.jpg",
                            IsAvailable = true,
                            Name = "Smoked Salmon Platter",
                            Price = 630000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 40,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Carpaccio bò với rucola, phô mai parmesan, và sốt mù tạt.",
                            FoodCategoryId = 12,
                            ImageUrl = "beef_carpaccio.jpg",
                            IsAvailable = true,
                            Name = "Beef Carpaccio",
                            Price = 440000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 41,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Filet Mignon steak với nước sốt đặc biệt.",
                            FoodCategoryId = 13,
                            ImageUrl = "filet_mignon.jpg",
                            IsAvailable = true,
                            Name = "Filet Mignon",
                            Price = 350000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 42,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ribeye steak chảo nước sốt tiêu xanh.",
                            FoodCategoryId = 13,
                            ImageUrl = "ribeye_steak.jpg",
                            IsAvailable = true,
                            Name = "Ribeye Steak",
                            Price = 290000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 43,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "T-bone steak với gia vị hảo hạng.",
                            FoodCategoryId = 13,
                            ImageUrl = "t_bone_steak.jpg",
                            IsAvailable = true,
                            Name = "T-bone Steak",
                            Price = 750000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 44,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "New York Strip steak với nước sốt hạt tiêu.",
                            FoodCategoryId = 13,
                            ImageUrl = "new_york_strip.jpg",
                            IsAvailable = true,
                            Name = "New York Strip",
                            Price = 380000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 45,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Porterhouse steak nướng chín với ớt và tỏi.",
                            FoodCategoryId = 13,
                            ImageUrl = "porterhouse_steak.jpg",
                            IsAvailable = true,
                            Name = "Porterhouse Steak",
                            Price = 620000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 46,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sirloin steak với sốt hành tỏi.",
                            FoodCategoryId = 13,
                            ImageUrl = "sirloin_steak.jpg",
                            IsAvailable = true,
                            Name = "Sirloin Steak",
                            Price = 550000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 47,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flank steak với gia vị tỏi và hạt tiêu.",
                            FoodCategoryId = 13,
                            ImageUrl = "flank_steak.jpg",
                            IsAvailable = true,
                            Name = "Flank Steak",
                            Price = 380000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 48,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prime Rib steak nướng chín với muối và hạt tiêu.",
                            FoodCategoryId = 13,
                            ImageUrl = "prime_rib_steak.jpg",
                            IsAvailable = true,
                            Name = "Prime Rib",
                            Price = 450000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 49,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Skirt steak với gia vị đặc biệt.",
                            FoodCategoryId = 13,
                            ImageUrl = "skirt_steak.jpg",
                            IsAvailable = true,
                            Name = "Skirt Steak",
                            Price = 420000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 50,
                            CreatedAt = new DateTime(2016, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chateaubriand steak với sốt nước sốt đậm đà.",
                            FoodCategoryId = 13,
                            ImageUrl = "chateaubriand_steak.jpg",
                            IsAvailable = true,
                            Name = "Chateaubriand",
                            Price = 670000f,
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("MAGOI.BusinessObjects.Models.FoodCategory", b =>
                {
                    b.Property<int>("FoodCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodCategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FoodCategoryId");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            FoodCategoryId = 1,
                            Description = "Lẩu Thái với hương vị đậm đà của nước lẩu Tom Yum.",
                            Name = "Lẩu Tom Yum"
                        },
                        new
                        {
                            FoodCategoryId = 2,
                            Description = "Lẩu Thái với sự hòa quyện của nước lẩu Tom Kha và sữa cô cocon.",
                            Name = "Lẩu Tom Kha"
                        },
                        new
                        {
                            FoodCategoryId = 3,
                            Description = "Lẩu Thái với nước lẩu xanh mát từ cà ri xanh.",
                            Name = "Lẩu Green Curry"
                        },
                        new
                        {
                            FoodCategoryId = 4,
                            Description = "Lẩu Thái với hương vị độc đáo của nước lẩu Red Curry.",
                            Name = "Lẩu Red Curry"
                        },
                        new
                        {
                            FoodCategoryId = 6,
                            Description = "Lẩu Thái với gia vị đặc trưng của cà ri Massaman.",
                            Name = "Lẩu Massaman"
                        },
                        new
                        {
                            FoodCategoryId = 7,
                            Description = "Một trong những món phở nổi tiếng với nước dùng thơm ngon và thịt bò mềm.",
                            Name = "Phở Bò"
                        },
                        new
                        {
                            FoodCategoryId = 8,
                            Description = "Món phở với nước dùng hương vị và thịt gà tươi ngon.",
                            Name = "Phở Gà"
                        },
                        new
                        {
                            FoodCategoryId = 9,
                            Description = "Phở dành cho người ăn chay, với nước dùng và nguyên liệu chay thơm ngon.",
                            Name = "Phở Chay"
                        },
                        new
                        {
                            FoodCategoryId = 10,
                            Description = "Phở với sườn nước dùng đậm đà và thịt sườn ngon mắt.",
                            Name = "Phở Sườn"
                        },
                        new
                        {
                            FoodCategoryId = 11,
                            Description = "Món salad tươi ngon với rau sống và sốt truyền thống.",
                            Name = "Salad"
                        },
                        new
                        {
                            FoodCategoryId = 12,
                            Description = "Các món khai vị hấp dẫn để bắt đầu bữa ăn.",
                            Name = "Món Khai Vị"
                        },
                        new
                        {
                            FoodCategoryId = 13,
                            Description = "Món lạnh ngon lành, phù hợp cho bữa ăn nhẹ.",
                            Name = "Món Lạnh"
                        },
                        new
                        {
                            FoodCategoryId = 14,
                            Description = "Các loại steak chất lượng cao, nướng hoặc nướng chín theo yêu cầu.",
                            Name = "Steak"
                        });
                });

            modelBuilder.Entity("MAGOI.BusinessObjects.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RestaurantId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RestaurantCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Address = "Số 5 Quan Hoa, Cầu Giấy, Hà Nội",
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mkt@mamagroup.vn",
                            Hotline = "02477748666",
                            IsAvailable = true,
                            Name = "Thái Deli",
                            RestaurantCategoryId = 1
                        },
                        new
                        {
                            RestaurantId = 2,
                            Address = "13 Lò Đúc, quận Hai Bà Trưng, Hà Nội",
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phothin1979hanoi@gmail.com",
                            Hotline = "0966657997",
                            IsAvailable = true,
                            Name = "Phở Thìn Lò Đúc",
                            RestaurantCategoryId = 2
                        },
                        new
                        {
                            RestaurantId = 3,
                            Address = "184 Hào Nam, Cát Linh, Đống Đa, Hà Nội",
                            CreatedAt = new DateTime(2015, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grill66steakhousevn@gmail.com",
                            Hotline = "0965401915",
                            IsAvailable = true,
                            Name = "Grille6 Steakhouse",
                            RestaurantCategoryId = 3
                        });
                });

            modelBuilder.Entity("demo.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int>("BillId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("TableID")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("demo.Models.Table", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TableID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("TableID");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableID = 1,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 1",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableID = 2,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 2",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableID = 3,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 3",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableID = 4,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 4",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableID = 5,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 5",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableID = 6,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 6",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableID = 7,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 7",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableID = 8,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 8",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableID = 9,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 9",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableID = 10,
                            CreatedAt = new DateTime(2018, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 10",
                            RestaurantId = 1
                        },
                        new
                        {
                            TableID = 11,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 1",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 12,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 2",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 13,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 3",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 14,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 4",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 15,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 5",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 16,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 6",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 17,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 7",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 18,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 8",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 19,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 9",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 20,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 10",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 21,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 11",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 22,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 12",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 23,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 13",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 24,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 14",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 25,
                            CreatedAt = new DateTime(2009, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 15",
                            RestaurantId = 2
                        },
                        new
                        {
                            TableID = 26,
                            CreatedAt = new DateTime(2015, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 1",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 27,
                            CreatedAt = new DateTime(2015, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 2",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 28,
                            CreatedAt = new DateTime(2015, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 3",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 29,
                            CreatedAt = new DateTime(2015, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 4",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 30,
                            CreatedAt = new DateTime(2015, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 5",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 31,
                            CreatedAt = new DateTime(2015, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 6",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 32,
                            CreatedAt = new DateTime(2015, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 7",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 33,
                            CreatedAt = new DateTime(2015, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 8",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 34,
                            CreatedAt = new DateTime(2015, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 9",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 35,
                            CreatedAt = new DateTime(2015, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 10",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 36,
                            CreatedAt = new DateTime(2015, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 11",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 37,
                            CreatedAt = new DateTime(2015, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 12",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 38,
                            CreatedAt = new DateTime(2015, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 13",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 39,
                            CreatedAt = new DateTime(2015, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 14",
                            RestaurantId = 3
                        },
                        new
                        {
                            TableID = 40,
                            CreatedAt = new DateTime(2015, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "Bàn 15",
                            RestaurantId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
